// ui/atoms/icon/icons-map.tsx

import {
  Search,
  User,
  Mail,
  Lock,
  Eye,
  EyeOff,
  AlertCircle,
  Check,
  X,
  Loader2,
  ChevronLeft,
  ChevronRight,
  Info,
  ChevronUp,
  ChevronDown,
  Send,
  Bell,
  LayoutDashboard,
  Building2,
  Grid2x2,
  Store,
  BarChart2,
  Receipt,
  Users,
  Settings,
  Menu,
  LogOut,
  BrushCleaning,
} from "lucide-react";
import type { IconName } from "./Icon.types";

export const ICONS_MAP: Record<IconName, React.ComponentType<any>> = {
  search: Search,
  user: User,
  email: Mail,
  lock: Lock,
  eye: Eye,
  "eye-off": EyeOff,
  alert: AlertCircle,
  check: Check,
  x: X,
  loader: Loader2,
  info: Info,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  send: Send,
  bell: Bell,
  "layout-dashboard": LayoutDashboard,
  "building-2": Building2,
  "grid-2x2": Grid2x2,
  store: Store,
  "bar-chart-2": BarChart2,
  receipt: Receipt,
  users: Users,
  settings: Settings,
  "log-out": LogOut,
  menu: Menu,
  clean: BrushCleaning,
};
