// core/constants/roles.ts

export const ROLE = {
  MANAGER: "MANAGER",
  SUPERVISOR: "SUPERVISOR",
  COORDINATOR: "COORDINATOR",
  COLLECTOR: "COLLECTOR",
  MERCHANT: "MERCHANT",
} as const;

export type ROLE = (typeof ROLE)[keyof typeof ROLE];

export const ROLE_HIERARCHY: Record<ROLE, ROLE[]> = {
  [ROLE.MANAGER]: [
    ROLE.MANAGER,
    ROLE.SUPERVISOR,
    ROLE.COORDINATOR,
    ROLE.COLLECTOR,
    ROLE.MERCHANT,
  ],
  [ROLE.SUPERVISOR]: [
    ROLE.SUPERVISOR,
    ROLE.COORDINATOR,
    ROLE.COLLECTOR,
    ROLE.MERCHANT,
  ],
  [ROLE.COORDINATOR]: [ROLE.COORDINATOR, ROLE.COLLECTOR, ROLE.MERCHANT],
  [ROLE.COLLECTOR]: [ROLE.COLLECTOR, ROLE.MERCHANT],
  [ROLE.MERCHANT]: [ROLE.MERCHANT],
};
