// core/constants/roles.ts

export const ROLE = {
  MANAGER: "GERENTE",
  SUPERVISOR: "SUPERVISOR",
  COORDINATOR: "COORDINADOR",
  COLLECTOR: "COBRADOR",
  MERCHANT: "COMERCIANTE",
  UNKNOWN: "DESCONOCIDO",
} as const;

export type ROLE = (typeof ROLE)[keyof typeof ROLE];

export const ROLE_HIERARCHY: Record<ROLE, ROLE[]> = {
  [ROLE.MANAGER]: [
    ROLE.MANAGER,
    ROLE.SUPERVISOR,
    ROLE.COORDINATOR,
    ROLE.COLLECTOR,
    ROLE.MERCHANT,
    ROLE.UNKNOWN,
  ],
  [ROLE.SUPERVISOR]: [
    ROLE.SUPERVISOR,
    ROLE.COORDINATOR,
    ROLE.COLLECTOR,
    ROLE.MERCHANT,
    ROLE.UNKNOWN,
  ],
  [ROLE.COORDINATOR]: [
    ROLE.COORDINATOR,
    ROLE.COLLECTOR,
    ROLE.MERCHANT,
    ROLE.UNKNOWN,
  ],
  [ROLE.COLLECTOR]: [ROLE.COLLECTOR, ROLE.MERCHANT, ROLE.UNKNOWN],
  [ROLE.MERCHANT]: [ROLE.MERCHANT, ROLE.UNKNOWN],
  [ROLE.UNKNOWN]: [ROLE.UNKNOWN],
};
